### ISSUE TITLE
Create contributing guide

### ISSUE THREAD

**Issue by danguilherme** [danguilherme/spotivy#15]
Create a simple contributing guide, which covers:

- how/when to open an issue;
- how to contribute with code (like always [basing from `develop`](https://github.com/danguilherme/spotivy/pull/10#pullrequestreview-163645290)).

**Comment by silvererudite** [comment]
hi @danguilherme ..I would like to work on this. Do you have any preference or special instructions for ex: things to include. Should I add it in the already existing readme file or create a separate contributing markdown file ?
