### ISSUE TITLE
Create issue and PR templates

### ISSUE THREAD

**Issue by danguilherme** [danguilherme/spotivy#16]
Make [contributions](https://github.com/danguilherme/spotivy/issues/15) a bit easier by using [issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository).

**Comment by dougfabris** [comment]
Hey @danguilherme your project is cool. Can I help with that?!

**Comment by danguilherme** [comment]
Sure thing! Just send a PR...

Don't need anything fancy, just a starting point, with placeholder for basic info, like package version, for instance. For inspiration: [webpack bug report template](https://github.com/webpack/webpack/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) (don't need to be based on that).

**Comment by mapalochibwe** [comment]
I will try my best to add value to your project. Are there any specific errors that you would love to focus on first?
