### ISSUE TITLE
GoodMusicVideoContent criteria

### ISSUE THREAD

**Issue by danicuki** [danguilherme/spotivy#8]
the criterion you use to consider a music video good is somehow weak. I suggest that you warn the users in the documentation that there is no certainty that the correct song will be download. What do you think?

https://github.com/danguilherme/spotivy/blob/54a1a2deb1e8da4b1554d1ba829e7f8184d6e778/youtube_search.js#L76

**Comment by danguilherme** [comment]
I totally agree!
In the [Spotivy release article](https://danguilherme.github.io/blog/spotivy/#encontrando-v-deo-de-qualidade) I covered that (only in portuguese for now), but this information would be useful in the README, no doubt.

Also, any suggestion to improve the "what is a good music video" algorithm is welcome!
